# Copyright (c) .NET Foundation and Contributors
# See LICENSE file in the project root for full license information.

# This workflow will periodically check .NET nanoFramework dependencies and updates them in the repository it's running.

name: Daily update dependencies

on:
  schedule:
  # At 00:00 UTC every Friday.
  - cron:  '00 00 * * 6'
  repository_dispatch:
    types: update-dependencies
  workflow_dispatch:

defaults:
  run:
    shell: pwsh

jobs:
  update-dotnet-preview:
    name: Update .NET nanoFramework dependencies
    timeout-minutes: 360 # Non default as samples repo it's huge and has lots of solutions to update!
    runs-on: windows-latest
    env:
      GITHUB_TOKEN: ${{ github.token }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Update dependencies
        uses: nanoframework/nanodu@v1
        with:
          solutionsToCheck: '*.sln'
          exclusionList: |
            device-listing
            Amqp.Samples
          workingDirectory: '${{ github.workspace }}/samples'
